"""add Koji tags

Revision ID: 723d9e77cb7b
Revises: 9c3fbfc5f9d2
Create Date: 2019-04-04 21:00:34.840171+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723d9e77cb7b'
down_revision = '9c3fbfc5f9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_builds',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tag', sa.String(), nullable=False),
                    sa.Column('build_nvr', sa.String(), nullable=False),
                    sa.Column('entity_name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_tag_builds_entity_name'), 'tag_builds', ['entity_name'], unique=False)
    op.create_table('tag_cache_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tag', sa.String(), nullable=False),
                    sa.Column('latest_event', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_tag_cache_items_tag'), 'tag_cache_items', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_cache_items_tag'), table_name='tag_cache_items')
    op.drop_table('tag_cache_items')
    op.drop_index(op.f('ix_tag_builds_entity_name'), table_name='tag_builds')
    op.drop_table('tag_builds')
    # ### end Alembic commands ###
